language: php

php:
  - '7.1'
  
services:
  - postgresql

before_script:
  - composer self-update
  - composer install --no-interaction
  - psql -c 'create database ralphwaldolibrary;' -U postgres
script:
  - vendor/bin/phpunit --coverage-text